import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {HashRouter, Navigate, NavLink, Route, Routes, useNavigate} from 'react-router-dom';
import axios from 'axios';
import {BarChart3, Bot, Calendar, ClipboardList, Contact, Headphones, LayoutDashboard, PhoneCall, Settings, BookOpen, LogOut} from 'lucide-react';
import './styles.css';
const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://localhost:8000'});
api.interceptors.request.use(c=>{const t=localStorage.getItem('vox_token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const nav=[['Dashboard','/',LayoutDashboard],['Live Calls','/live',PhoneCall],['Call History','/calls',ClipboardList],['Contacts','/contacts',Contact],['Appointments','/appointments',Calendar],['AI Agent','/agent',Bot],['Knowledge Base','/knowledge',BookOpen],['Analytics','/analytics',BarChart3],['Settings','/settings',Settings]];
function Shell({children}){const n=useNavigate();return <div className="shell"><aside><div className="brand"><span>V</span> VoxAgent</div><p className="workspace">OPERATIONS CONSOLE</p>{nav.map(([label,to,I])=><NavLink key={to} to={to} end={to==='/' }><I size={18}/>{label}</NavLink>)}<button className="logout" onClick={()=>{localStorage.clear();n('/login')}}><LogOut size={18}/>Logout</button></aside><main><header><div><p className="eyebrow">DEMO MODE</p><h1>AI voice operations</h1></div><div className="status"><i/> Systems operational</div></header>{children}</main></div>}
function Login(){const [error,setError]=useState('');const n=useNavigate();const submit=async e=>{e.preventDefault();const values=new FormData(e.currentTarget);try{const r=await api.post('/api/auth/login',{email:String(values.get('email')||''),password:String(values.get('password')||'')});localStorage.setItem('vox_token',r.data.access_token);n('/')}catch(err){setError(err.response?.data?.detail||'Unable to sign in. Use the Demo Mode credentials below.')}};return <div className="login"><form onSubmit={submit}><div className="logo">V</div><h1>Welcome to VoxAgent</h1><p>Sign in to the voice operations console.</p>{error&&<div className="error">{typeof error==='string'?error:'Please check the entered credentials.'}</div>}<label>Email<input name="email" type="email" defaultValue="admin@voxagent.local" required/></label><label>Password<input name="password" type="password" defaultValue="DemoPass123!" required/></label><button>Sign in</button><small>Demo Mode: admin@voxagent.local / DemoPass123!</small></form></div>}
const fmt=s=>s?new Date(s).toLocaleDateString():'—';
function Dashboard(){const [data,setData]=useState();useEffect(()=>{api.get('/api/dashboard').then(r=>setData(r.data))},[]);if(!data)return <Loading/>;const m=data.metrics;return <><div className="intro"><div><h2>Good morning, Administrator</h2><p>Monitor your calls, appointments, and AI performance in real time.</p></div><span className="demo">Simulated environment</span></div><section className="metrics">{[['Total calls',m.total_calls],['Successful calls',m.successful_calls],['Appointments booked',m.appointments_booked],['AI resolution rate',`${m.resolution_rate}%`]].map(x=><article key={x[0]}><p>{x[0]}</p><strong>{x[1]}</strong><small>Live operational metric</small></article>)}</section><section className="panel"><div className="section-head"><h2>Recent calls</h2><NavLink to="/calls">View all</NavLink></div><CallTable rows={data.recent_calls}/></section></>}
function CallTable({rows=[]}){return <div className="table-wrap"><table><thead><tr><th>Caller</th><th>Direction</th><th>Status</th><th>Intent</th><th>Date</th></tr></thead><tbody>{rows.length?rows.map(c=><tr key={c.id}><td><b>{c.phone_number}</b></td><td>{c.direction}</td><td><span className={'badge '+c.status}>{c.status}</span></td><td>{c.intent||'—'}</td><td>{fmt(c.created_at)}</td></tr>):<tr><td colSpan="5" className="empty">No calls yet. Start a simulated call from Live Calls.</td></tr>}</tbody></table></div>}
function Calls(){const [calls,setCalls]=useState([]);useEffect(()=>{api.get('/api/calls').then(r=>setCalls(r.data))},[]);return <section className="panel"><div className="section-head"><div><h2>Call history</h2><p>Searchable records for every conversation.</p></div></div><CallTable rows={calls}/></section>}
function Live(){const [phone,setPhone]=useState('+15550102345'),[call,setCall]=useState(),[text,setText]=useState('I would like to book an appointment'),[messages,setMessages]=useState([]);const start=async()=>{const r=await api.post('/api/calls/outbound',{phone_number:phone});setCall(r.data);setMessages([{role:'assistant',content:'Hello, thank you for calling VoxAgent. How may I help you today?'}])};const send=async e=>{e.preventDefault();if(!call)return;const r=await api.post(`/api/calls/${call.id}/messages`,{content:text});setMessages(x=>[...x,{role:'caller',content:text},{role:'assistant',content:r.data.reply}]);setText('')};const end=async()=>{await api.post(`/api/calls/${call.id}/complete`);setCall(null)};return <div className="live-grid"><section className="panel live"><div className="section-head"><div><p className="eyebrow">{call?'ACTIVE DEMO CALL':'OUTBOUND SIMULATOR'}</p><h2>{call?call.phone_number:'Start a simulated call'}</h2></div>{call&&<span className="badge in-progress">Connected</span>}</div>{!call?<div className="call-start"><label>Customer phone number<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><button onClick={start}><PhoneCall size={18}/> Start demo call</button></div>:<><div className="transcript">{messages.map((m,i)=><div key={i} className={'bubble '+m.role}><b>{m.role==='assistant'?'Alex · AI':'Caller'}</b><p>{m.content}</p></div>)}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type simulated caller speech..."/><button>Send</button><button type="button" className="danger" onClick={end}>End</button></form></>}</section><aside className="panel insights"><h2>Live intelligence</h2><div><span>Agent status</span><b>{call?'Listening':'Ready'}</b></div><div><span>Speech pipeline</span><b>{call?'Demo simulation':'Idle'}</b></div><div><span>Telephony</span><b>Demo Mode</b></div><p>Realtime dashboard events are delivered over WebSockets when connected.</p></aside></div>}
function Crud({kind,endpoint,fields}){const [items,setItems]=useState([]);const load=()=>api.get(endpoint).then(r=>setItems(r.data));useEffect(load,[]);const submit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));await api.post(endpoint,o);e.target.reset();load()};return <section className="panel"><div className="section-head"><div><h2>{kind}</h2><p>Manage shared data used by the voice agent.</p></div></div><form className="inline-form" onSubmit={submit}>{fields.map(f=><input key={f} name={f} placeholder={f.replace('_',' ')} required={f!=='notes'}/>) }<button>Add</button></form><div className="records">{items.length?items.map(i=><article key={i.id}><b>{i.title||i.customer_name||i.name}</b><span>{i.phone||i.category||`${i.date} · ${i.time}`}</span><small>{i.status||i.email||i.content}</small></article>):<p className="empty">Nothing here yet.</p>}</div></section>}
function Agent(){const [agent,setAgent]=useState();useEffect(()=>api.get('/api/agents').then(r=>setAgent(r.data[0])),[]);if(!agent)return <Loading/>;return <section className="panel"><h2>AI agent configuration</h2><p className="muted">Changes are restricted to administrators and control the live receptionist.</p><form className="config" onSubmit={async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));await api.put(`/api/agents/${agent.id}`,{...agent,...o,enabled:true});alert('Agent configuration saved.')}}>{[['name','Agent name'],['greeting','Greeting'],['voice','Voice'],['language','Language'],['system_prompt','System prompt']].map(([key,label])=><label key={key}>{label}{key==='system_prompt'?<textarea name={key} defaultValue={agent[key]}/>:<input name={key} defaultValue={agent[key]}/>}</label>)}<button>Save configuration</button></form></section>}
function Analytics(){return <section className="panel"><h2>Analytics</h2><p className="muted">Metrics become available as calls are completed. Demo Mode data is visibly labelled throughout the product.</p><div className="chart"><span>Calls by day</span><div className="bars">{[28,42,18,65,48,75,55].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div></section>}
function Loading(){return <div className="loading">Loading VoxAgent data…</div>};
function ProtectedApp(){if(!localStorage.getItem('vox_token'))return <Navigate to="/login" replace/>;return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/live" element={<Live/>}/><Route path="/calls" element={<Calls/>}/><Route path="/contacts" element={<Crud kind="Contacts" endpoint="/api/contacts" fields={['name','phone','email','company','notes']}/>}/><Route path="/appointments" element={<Crud kind="Appointments" endpoint="/api/appointments" fields={['customer_name','phone','date','time','notes']}/>}/><Route path="/knowledge" element={<Crud kind="Knowledge base" endpoint="/api/knowledge" fields={['title','content','category']}/>}/><Route path="/agent" element={<Agent/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/settings" element={<section className="panel"><h2>Settings</h2><p className="muted">Configure environment variables for production integrations. Secrets are never exposed in this dashboard.</p></section>}/></Routes></Shell>}
function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="*" element={<ProtectedApp/>}/></Routes>};createRoot(document.getElementById('root')).render(<HashRouter><App/></HashRouter>);
